AWSTemplateFormatVersion: '2010-09-09'
Description: 'Base stack for 1NCE Data Streamer Kinesis to get started'
Parameters:
  KinesisStreamName:
    Type: String
    Default: 1nce-data-stream
    Description: Enter the Kinesis Stream name. This will be prefixed by your account id.
    MaxLength: 50
  DatastreamerRoleARN:
    Type: String
    Default: arn:aws:iam::884047677700:role/datastreamer
    Description: The 1nce role that will be allowed to assume the role defined here with the purpose of submitting data. This role most likely doesn't change.
  AllowedExternalID:
    Type: String
    Description: Enter external ID that matches the 
Resources:
  KinesisStream:
    Type: 'AWS::Kinesis::Stream'
    Properties:
      Name: !Sub '${AWS::AccountId}-${KinesisStreamName}'
      ShardCount: 1

  DataStreamerRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Ref DatastreamerRoleARN
            Action:
              - 'sts:AssumeRole'
            Condition: 
              "ForAnyValue:StringEquals": 
                "sts:ExternalId":
                  - !Ref AllowedExternalID
      Policies:
        - PolicyName: allow-put-1nce-data-streamer-stream
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - 'Kinesis:PutRecord'
                  - 'Kinesis:PutRecords'
                Resource: !Sub 'arn:aws:kinesis:::${KinesisStream}/*'

  KinesisStreamNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /1nce-data-streamer-kinesis-stream/name
      Type: String
      Value: !Ref KinesisStream
      Description: The name of the 1nce data streamer kinesis stream
      Tags:
        heritage: cloudformation