AWSTemplateFormatVersion: '2010-09-09'
Description: 'Base stack for 1NCE Data Streamer S3 to get started'
Parameters:
  S3BucketName:
    Type: String
    Default: 1nce-data-streamer
    Description: Enter the bucket name. This will be prefixed by your account name.
    MaxLength: 50
  DatastreamerRoleARN:
    Type: String
    Default: arn:aws:iam::884047677700:role/1nce-datastreamer
    Description: The 1nce role that will be allowed to assume the role defined here with the purpose of submitting data. This role most likely doesn't change.
  AllowedExternalID:
    Type: String
    Description: Enter external ID that matches the 1NCE internal Organisation ID. It follows the structure of org-1234. When creating via the Customer Portal it will be automaticall added.
Resources:
  EncryptedS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'AES256'

  DataStreamerRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Ref DatastreamerRoleARN
            Action:
              - 'sts:AssumeRole'
            Condition: 
              "ForAnyValue:StringEquals": 
                "sts:ExternalId":
                  - !Ref AllowedExternalID
      Policies:
        - PolicyName: !Join ['-', ['allow-write-1nce', !Select [4, !Split ['-', !Select [2, !Split ['/', !Ref AWS::StackId]]]]]]
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 's3:PutObject'
                Resource: !Sub 'arn:aws:s3:::${EncryptedS3Bucket}/*'

  S3BucketNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: !Ref EncryptedS3Bucket
      Description: The name of the 1nce data streamer bucket
      Tags:
        heritage: cloudformation

  DataStreamerRoleParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: !GetAtt DataStreamerRole.Arn
      Description: The Data Streamer IAM Role of the 1nce data streamer S3 stream
      Tags:
        heritage: cloudformation

Outputs:
  AWSRegion:
    Description: AWS Region for the Data Streamer. Input in 1NCE Portal during configuration.
    Value: !Ref "AWS::Region"
  S3Bucket:
    Description: S3 Bucket Name for the Data Streamer. Input in 1NCE Portal during configuration.
    Value: !Ref EncryptedS3Bucket
  IAMRoleARN:
    Description: IAM Role ARN for the Data Streamer. Input in 1NCE Portal during configuration.
    Value: !GetAtt DataStreamerRole.Arn
